### ISSUE TITLE
[FIX] 윈도우에서 yarn build:all 안되는 현상

### ISSUE THREAD

**Issue by hwgyun** [ahachulTeam/ahachul_web#222]
`command not found: rm` 문구가 뜨면서 빌드 실패하는 현상

**Comment by createhb21** [comment]
@hwgyun 



`rimraf`를 프로젝트 의존성으로 추가하고, 모든 환경에서 사용하도록 설정.

1. 먼저, `rimraf`를 프로젝트의 개발 의존성으로 추가

```shellscript
yarn add -D rimraf
```

2. 각 패키지의 `package.json`에서 `clean` 스크립트를 다음과 같이 수정

```json
"clean": "rimraf dist"
```
